(load "list.scm")
(load "super_abstract.scm")
(define (number-pair n)
    (accumulate append nil (map (lambda (i) (map (lambda (j) (list i j))
                                                  (enumerate-interval 1 (- i 1))))
     (enumerate-interval 1 n)))
)