(define (equal? x y)
    (define (not-pair? a)
        (not (pair? a))
    )
    (cond ((and (not-pair? x) (not-pair? y)) (eq? x y))
        ((and (pair? x) (pair? y)) (and (equal? (car x) (car y)) (equal? (cdr x) (cdr y))))
        (else #f)
    )
)